log4j:
    category:
        org:
            springframework:
                data:
                    document:
                        mongodb: DEBUG
logging:
    level:
        org:
            springframework:
                data:
                    mongodb:
                        core:
                            MongoTemplate: DEBUG
                            ReactiveMongoTemplate: DEBUG
                        repository:
                            query: DEBUG
spring:
    profiles: dev
    data:
        mongodb:
            auto-index-creation: true
            database: dev
---
spring:
    profiles: test
    data:
        mongodb:
            auto-index-creation: true
            database: test
log4j:
    category:
        org:
            springframework:
                data:
                    document:
                        mongodb: DEBUG
logging:
    level:
        org:
            springframework:
                data:
                    mongodb:
                        core:
                            MongoTemplate: DEBUG
                            ReactiveMongoTemplate: DEBUG
                        repository:
                            query: DEBUG
